export const DATA_FETCHED = 'DATA_FETCHED';
export const DATA_SUCCEEDED = 'DATA_SUCCEEDED';
export const DATA_FAILED = 'DATA_FAILED';

export const NEXT_QUESTION = 'NEXT_QUESTION';
export const PREV_QUESTION = 'PREV_QUESTION';
export const TOGGLE_QUESTION = 'TOGGLE_QUESTION';
export const TOGGLE_ANSWER = 'TOGGLE_ANSWER';